import { AppProvider } from "../components/menu/AppContext";
import "./globals.css";
import Header from '../components/layout/Header';
import { DM_Sans } from 'next/font/google'; // Importar fuente DM Sans
import Whatsapp from '../components/icons/Whatsapp'
import Footer from '../components/layout/Footer'

const dmSans = DM_Sans({ subsets: ['latin'] }); // Configurar la fuente

export const metadata = {
  title: "Electronica Argentina",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${dmSans.className}`}> {/* Aplicar fuente */}
        <AppProvider>
          <Header />
          <Whatsapp />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
